library nhs_authentication_response;

import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';
import 'package:nhs_login/src/models/authentication/nhs_authentication_error.dart';
import 'package:nhs_login/src/models/nhs_response_error.dart';
import 'package:nhs_login/src/models/serializers.dart';
import 'package:nhs_login/src/nhs_authentication.dart';

part 'nhs_authentication_response.g.dart';

/// The Authentication Response returns this parameters by adding them as query
/// parameters to the redirect_uri specified in the [NhsAuthentication].
abstract class NhsAuthenticationResponse
    implements
        Built<NhsAuthenticationResponse, NhsAuthenticationResponseBuilder>,
        NhsResponseError<NhsAuthenticationError> {
  factory NhsAuthenticationResponse(
          [void updates(NhsAuthenticationResponseBuilder b)]) =
      _$NhsAuthenticationResponse;

  factory NhsAuthenticationResponse.fromJson(Map<String, dynamic> json) =>
      serializers.deserializeWith(serializer, json);

  NhsAuthenticationResponse._();

  /// The authorization code generated by the NHS Login Platform.
  ///
  /// The authorization code MUST expire shortly after it is issued to mitigate
  /// the risk of leaks. A maximum authorization code lifetime of 10 minutes is
  /// RECOMMENDED.
  ///
  /// The client MUST NOT use the authorization code more than once. If an
  /// authorization code is used more than once, the Platform MUST deny the
  /// request and SHOULD revoke (when possible) all tokens previously issued
  /// based on that authorization code.
  ///
  /// The authorization code is bound to the client identifier and redirection
  /// URI
  @nullable
  String get code;

  /// If the "state" parameter was present in the client authorization request,
  /// then it MUST be the exact value received from the client, otherwise not
  /// included
  String get state;

  /// If the authentication request is denied or fails, the authorisation server
  /// informs the client using this parameter.
  ///
  /// Unless the Redirection URI is invalid, the Authorisation Server returns
  /// the client to the Redirection URI specified in the Authentication Request
  /// with the error and state parameters.
  @override
  @nullable
  NhsAuthenticationError get error;

  /// Description of the error
  @override
  @nullable
  @BuiltValueField(wireName: 'error_description')
  String get errorDescription;

  /// URI of a web page that includes additional information about the error
  @override
  @nullable
  @BuiltValueField(wireName: 'error_uri')
  String get errorUri;

  /// Any other parameters that were return by the Authorisation Server
  @nullable
  Map<String, String> get otherParams;

  bool get isError => code == null || code.isEmpty || error != null;

  @memoized
  Map<String, dynamic> get json => serializers.serializeWith(serializer, this);

  static Serializer<NhsAuthenticationResponse> get serializer =>
      _$nhsAuthenticationResponseSerializer;
}
